In [1]:
import numpy as np

In [3]:
data = np.random.randint(10, 20, (10, 5))

In [4]:
data

array([[16, 16, 19, 12, 10],
       [13, 10, 19, 12, 17],
       [18, 16, 15, 18, 14],
       [19, 15, 14, 15, 19],
       [14, 18, 17, 14, 18],
       [17, 14, 15, 17, 14],
       [16, 17, 11, 15, 16],
       [14, 16, 14, 17, 19],
       [19, 10, 12, 17, 17],
       [19, 19, 16, 12, 13]])

In [8]:
data.sum()   # Gives the sum of all the elements of the array

774

In [9]:
data.sum(axis=0)  # Gives the sum of elements about axis=0, i.e., the sum of every column of the array

array([165, 151, 152, 149, 157])

In [11]:
data.sum(axis=1)   # Gives the sum of elements about axis=1, i.e., the sum of every row of the array

array([73, 71, 81, 82, 81, 77, 75, 80, 75, 79])

In [20]:
data.min(), data.max()

(10, 19)

In [21]:
data.min(axis=0)

array([13, 10, 11, 12, 10])

In [22]:
data.max(axis=1)

array([19, 19, 18, 19, 18, 17, 17, 19, 19, 19])

In [14]:
data.mean()

15.48

In [15]:
np.median(data)

16.0

In [16]:
np.min(data), np.max(data), np.sum(data), np.median(data)

(10, 19, 774, 16.0)

In [17]:
np.min(data, axis=0)

array([13, 10, 11, 12, 10])

In [23]:
np.max(data, axis=1)

array([19, 19, 18, 19, 18, 17, 17, 19, 19, 19])

In [24]:
np.sort(data, axis=0)

array([[13, 10, 11, 12, 10],
       [14, 10, 12, 12, 13],
       [14, 14, 14, 12, 14],
       [16, 15, 14, 14, 14],
       [16, 16, 15, 15, 16],
       [17, 16, 15, 15, 17],
       [18, 16, 16, 17, 17],
       [19, 17, 17, 17, 18],
       [19, 18, 19, 17, 19],
       [19, 19, 19, 18, 19]])

In [26]:
np.sort(data)   # By default, it sorts about the last axis. In this case, last axis=1

array([[10, 12, 16, 16, 19],
       [10, 12, 13, 17, 19],
       [14, 15, 16, 18, 18],
       [14, 15, 15, 19, 19],
       [14, 14, 17, 18, 18],
       [14, 14, 15, 17, 17],
       [11, 15, 16, 16, 17],
       [14, 14, 16, 17, 19],
       [10, 12, 17, 17, 19],
       [12, 13, 16, 19, 19]])

In [29]:
np.argsort(data)   # Returns the indices that would sort an array.

array([[4, 3, 0, 1, 2],
       [1, 3, 0, 4, 2],
       [4, 2, 1, 0, 3],
       [2, 1, 3, 0, 4],
       [0, 3, 2, 1, 4],
       [1, 4, 2, 0, 3],
       [2, 3, 0, 4, 1],
       [0, 2, 1, 3, 4],
       [1, 2, 3, 4, 0],
       [3, 4, 2, 0, 1]], dtype=int64)